apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-inventory
  namespace: {{ .Values.namespace }}
  labels:
    subnet.node: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
      app.kubernetes.io/instance: inventory-service
      app.kubernetes.io/component: operator
      app.kubernetes.io/part-of: provider
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory
        app.kubernetes.io/instance: inventory-service
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: provider
    spec:
      serviceAccountName: operator-inventory
      containers:
        - name: operator-inventory
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "./subnet"
          args:
            - "k8s-services"
            - "operator"
            - "inventory"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AP_CONFIG
              value: /subnet/config.yaml
            - name: AP_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AP_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8080
              name: rest
              protocol: TCP
            - containerPort: 8081
              name: grpc
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /subnet
      volumes:
        - name: config
          configMap:
            name: operator-inventory
