apiVersion: v2
name: subnet-operator-inventory
description: A Helm chart for Subnet Operator Inventory - Kubernetes operator for managing subnet inventory
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - subnet
  - operator
  - kubernetes
  - network
maintainers:
  - name: Subnet Operator Team
home: https://github.com/unicornultrafoundation/subnet-node
sources:
  - https://github.com/unicornultrafoundation/subnet-node

